In [2]:
import pandas as pd

df1 = pd.read_csv('boro/statenIsland_final.csv')
df2 = pd.read_csv('boro/manhattan_final.csv')
df3 = pd.read_csv('boro/brooklyn_final.csv')
df4 = pd.read_csv('boro/bronx_final.csv')
df5 = pd.read_csv('boro/queens_final.csv')

df = pd.concat([df1,df2,df3,df4,df5])
df

,6_Alphabet City,6_Battery Park,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,Unnamed: 0,ds,y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2015-01-01 02:54:38,1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2015-01-27 11:43:24,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2015-01-29 05:52:21,1
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2015-03-14 11:47:00,1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2015-03-27 15:56:00,1
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2015-04-08 08:20:00,1
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2015-04-08 13:42:00,1
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2015-04-10 13:32:00,1
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2015-04-21 00:10:00,1
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2015-04-21 22:48:00,1
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2015-05-04 10:25:00,1
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,2015-05-05 06:53:00,1
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,2015-05-11 12:29:00,1
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,2015-05-11 22:34:00,1
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,2015-05-24 00:03:00,1
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,2015-05-26 04:00:00,1
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,2015-06-03 08:16:00,1
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,2015-06-06 00:39:00,1
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,2015-06-14 00:46:00,1
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,2015-06-16 23:03:00,1
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,2015-06-17 15:39:00,1
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,2015-06-20 18:51:00,1
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,2015-06-21 13:24:00,1
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,2015-06-25 04:34:00,1
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,2015-06-27 21:06:00,1
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,2015-06-27 21:15:00,1
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,2015-01-01 02:13:26,1
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,2015-01-01 02:30:07,1
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,2015-01-02 08:24:33,1
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,2015-01-02 19:43:12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288314,2015-06-30 08:26:00,5
288315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288315,2015-06-30 08:56:00,2
288316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288316,2015-06-30 09:09:00,4
288317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288317,2015-06-30 09:41:00,6
288318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288318,2015-06-30 10:20:00,1
288319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288319,2015-06-30 11:03:00,2
288320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288320,2015-06-30 11:32:00,1
288321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288321,2015-06-30 12:20:00,2
288322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288322,2015-06-30 12:36:00,2
288323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288323,2015-06-30 13:25:00,3
288324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288324,2015-06-30 13:35:00,4
288325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288325,2015-06-30 14:27:00,4
288326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288326,2015-06-30 14:37:00,2
288327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288327,2015-06-30 15:07:00,2
288328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288328,2015-06-30 15:44:00,1
288329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288329,2015-06-30 16:01:00,6
288330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288330,2015-06-30 16:45:00,4
288331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288331,2015-06-30 17:33:00,2
288332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288332,2015-06-30 18:12:00,1
288333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288333,2015-06-30 19:00:00,4
288334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288334,2015-06-30 19:06:00,6
288335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288335,2015-06-30 19:43:00,2
288336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288336,2015-06-30 20:26:00,4
288337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288337,2015-06-30 20:56:00,2
288338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288338,2015-06-30 21:24:00,4
288339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288339,2015-06-30 21:45:00,7
288340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288340,2015-06-30 22:03:00,2
288341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288341,2015-06-30 22:44:00,6
288342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288342,2015-06-30 23:26:00,6
288343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,1.0,288343,2015-06-30 23:41:00,3

In [4]:
df.loc[df['7_Arden Heights'] == 1]

,6_Alphabet City,6_Battery Park,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,Unnamed: 0,ds,y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2015-01-01 02:54:38,1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2015-01-27 11:43:24,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2015-01-29 05:52:21,1
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2015-03-14 11:47:00,1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2015-03-27 15:56:00,1
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2015-04-08 08:20:00,1
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2015-04-08 13:42:00,1
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2015-04-10 13:32:00,1
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2015-04-21 00:10:00,1
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2015-04-21 22:48:00,1
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2015-05-04 10:25:00,1
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,2015-05-05 06:53:00,1
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,2015-05-11 12:29:00,1
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,2015-05-11 22:34:00,1
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,2015-05-24 00:03:00,1
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,2015-05-26 04:00:00,1
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,2015-06-03 08:16:00,1
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,2015-06-06 00:39:00,1
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,2015-06-14 00:46:00,1
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,2015-06-16 23:03:00,1
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,2015-06-17 15:39:00,1
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,2015-06-20 18:51:00,1
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,2015-06-21 13:24:00,1
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,2015-06-25 04:34:00,1
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,2015-06-27 21:06:00,1
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,2015-06-27 21:15:00,1

In [7]:
df.fillna(0, inplace=True)
df

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/arraysetops.py:472: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

,6_Alphabet City,6_Battery Park,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,Unnamed: 0,ds,y
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2015-01-01 02:54:38,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,2015-01-27 11:43:24,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,2015-01-29 05:52:21,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,2015-03-14 11:47:00,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4,2015-03-27 15:56:00,1
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5,2015-04-08 08:20:00,1
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,2015-04-08 13:42:00,1
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,2015-04-10 13:32:00,1
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8,2015-04-21 00:10:00,1
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9,2015-04-21 22:48:00,1
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,2015-05-04 10:25:00,1
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11,2015-05-05 06:53:00,1
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12,2015-05-11 12:29:00,1
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13,2015-05-11 22:34:00,1
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14,2015-05-24 00:03:00,1
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15,2015-05-26 04:00:00,1
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16,2015-06-03 08:16:00,1
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17,2015-06-06 00:39:00,1
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18,2015-06-14 00:46:00,1
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19,2015-06-16 23:03:00,1
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20,2015-06-17 15:39:00,1
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,2015-06-20 18:51:00,1
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22,2015-06-21 13:24:00,1
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23,2015-06-25 04:34:00,1
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24,2015-06-27 21:06:00,1
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25,2015-06-27 21:15:00,1
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26,2015-01-01 02:13:26,1
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27,2015-01-01 02:30:07,1
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28,2015-01-02 08:24:33,1
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29,2015-01-02 19:43:12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288314,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288314,2015-06-30 08:26:00,5
288315,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288315,2015-06-30 08:56:00,2
288316,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288316,2015-06-30 09:09:00,4
288317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288317,2015-06-30 09:41:00,6
288318,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288318,2015-06-30 10:20:00,1
288319,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288319,2015-06-30 11:03:00,2
288320,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288320,2015-06-30 11:32:00,1
288321,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288321,2015-06-30 12:20:00,2
288322,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288322,2015-06-30 12:36:00,2
288323,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288323,2015-06-30 13:25:00,3
288324,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288324,2015-06-30 13:35:00,4
288325,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288325,2015-06-30 14:27:00,4
288326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288326,2015-06-30 14:37:00,2
288327,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288327,2015-06-30 15:07:00,2
288328,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288328,2015-06-30 15:44:00,1
288329,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288329,2015-06-30 16:01:00,6
288330,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288330,2015-06-30 16:45:00,4
288331,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288331,2015-06-30 17:33:00,2
288332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288332,2015-06-30 18:12:00,1
288333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288333,2015-06-30 19:00:00,4
288334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288334,2015-06-30 19:06:00,6
288335,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288335,2015-06-30 19:43:00,2
288336,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288336,2015-06-30 20:26:00,4
288337,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288337,2015-06-30 20:56:00,2
288338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288338,2015-06-30 21:24:00,4
288339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288339,2015-06-30 21:45:00,7
288340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288340,2015-06-30 22:03:00,2
288341,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288341,2015-06-30 22:44:00,6
288342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288342,2015-06-30 23:26:00,6
288343,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,288343,2015-06-30 23:41:00,3

In [10]:
df=df.drop(['Unnamed: 0'],axis=1)
df

,6_Alphabet City,6_Battery Park,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Willets Point,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,ds,y
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-01-01 02:54:38,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-01-27 11:43:24,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-01-29 05:52:21,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-03-14 11:47:00,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-03-27 15:56:00,1
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-04-08 08:20:00,1
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-04-08 13:42:00,1
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-04-10 13:32:00,1
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-04-21 00:10:00,1
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-04-21 22:48:00,1
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-05-04 10:25:00,1
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-05-05 06:53:00,1
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-05-11 12:29:00,1
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-05-11 22:34:00,1
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-05-24 00:03:00,1
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-05-26 04:00:00,1
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-03 08:16:00,1
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-06 00:39:00,1
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-14 00:46:00,1
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-16 23:03:00,1
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-17 15:39:00,1
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-20 18:51:00,1
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-21 13:24:00,1
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-25 04:34:00,1
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-27 21:06:00,1
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-06-27 21:15:00,1
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-01-01 02:13:26,1
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-01-01 02:30:07,1
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-01-02 08:24:33,1
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-01-02 19:43:12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288314,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 08:26:00,5
288315,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 08:56:00,2
288316,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 09:09:00,4
288317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 09:41:00,6
288318,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 10:20:00,1
288319,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 11:03:00,2
288320,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 11:32:00,1
288321,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 12:20:00,2
288322,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 12:36:00,2
288323,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 13:25:00,3
288324,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 13:35:00,4
288325,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 14:27:00,4
288326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 14:37:00,2
288327,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 15:07:00,2
288328,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 15:44:00,1
288329,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 16:01:00,6
288330,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 16:45:00,4
288331,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 17:33:00,2
288332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 18:12:00,1
288333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 19:00:00,4
288334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 19:06:00,6
288335,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 19:43:00,2
288336,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 20:26:00,4
288337,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 20:56:00,2
288338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 21:24:00,4
288339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 21:45:00,7
288340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 22:03:00,2
288341,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 22:44:00,6
288342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 23:26:00,6
288343,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2015-06-30 23:41:00,3

In [11]:
cols = df.columns.tolist()
tmp = cols[-1]
tmp2 = cols[-2]
cols[-1] = cols[1]
cols[-2] = cols[0]
cols[0] = tmp2
cols[1] = tmp

df=df[cols]
df

,ds,y,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Willets Point,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,6_Alphabet City,6_Battery Park
0,2015-01-01 02:54:38,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-27 11:43:24,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-01-29 05:52:21,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-03-14 11:47:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-03-27 15:56:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2015-04-08 08:20:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2015-04-08 13:42:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2015-04-10 13:32:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2015-04-21 00:10:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2015-04-21 22:48:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2015-05-04 10:25:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2015-05-05 06:53:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2015-05-11 12:29:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2015-05-11 22:34:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2015-05-24 00:03:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2015-05-26 04:00:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2015-06-03 08:16:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2015-06-06 00:39:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2015-06-14 00:46:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2015-06-16 23:03:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2015-06-17 15:39:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2015-06-20 18:51:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2015-06-21 13:24:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2015-06-25 04:34:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2015-06-27 21:06:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2015-06-27 21:15:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2015-01-01 02:13:26,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2015-01-01 02:30:07,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2015-01-02 08:24:33,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2015-01-02 19:43:12,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288314,2015-06-30 08:26:00,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288315,2015-06-30 08:56:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288316,2015-06-30 09:09:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288317,2015-06-30 09:41:00,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288318,2015-06-30 10:20:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288319,2015-06-30 11:03:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288320,2015-06-30 11:32:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288321,2015-06-30 12:20:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288322,2015-06-30 12:36:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288323,2015-06-30 13:25:00,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288324,2015-06-30 13:35:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288325,2015-06-30 14:27:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288326,2015-06-30 14:37:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288327,2015-06-30 15:07:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288328,2015-06-30 15:44:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288329,2015-06-30 16:01:00,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288330,2015-06-30 16:45:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288331,2015-06-30 17:33:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288332,2015-06-30 18:12:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288333,2015-06-30 19:00:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288334,2015-06-30 19:06:00,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288335,2015-06-30 19:43:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288336,2015-06-30 20:26:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288337,2015-06-30 20:56:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288338,2015-06-30 21:24:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288339,2015-06-30 21:45:00,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288340,2015-06-30 22:03:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288341,2015-06-30 22:44:00,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288342,2015-06-30 23:26:00,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
288343,2015-06-30 23:41:00,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [12]:
df['Date'] = pd.to_datetime(df['ds'])
df=df.sort_values(by='Date')
df=df.drop(['Date'],axis=1)
df

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,ds,y,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Willets Point,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,6_Alphabet City,6_Battery Park
77488,2015-01-01 00:00:29,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63794,2015-01-01 00:00:38,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234906,2015-01-01 00:00:53,47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
150977,2015-01-01 00:01:08,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36702,2015-01-01 00:01:19,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5248,2015-01-01 00:01:23,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122895,2015-01-01 00:01:32,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
254914,2015-01-01 00:01:34,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299791,2015-01-01 00:01:37,41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118304,2015-01-01 00:01:41,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43880,2015-01-01 00:01:44,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121584,2015-01-01 00:01:53,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49596,2015-01-01 00:02:12,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,2015-01-01 00:02:34,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
325289,2015-01-01 00:03:03,38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
282541,2015-01-01 00:03:03,50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144261,2015-01-01 00:03:16,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
430904,2015-01-01 00:03:22,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34829,2015-01-01 00:03:29,11,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
506867,2015-01-01 00:03:33,31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
312408,2015-01-01 00:03:43,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249818,2015-01-01 00:03:49,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87844,2015-01-01 00:03:56,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,2015-01-01 00:03:58,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
113485,2015-01-01 00:04:01,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10753,2015-01-01 00:04:02,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74819,2015-01-01 00:04:29,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42519,2015-01-01 00:04:35,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119695,2015-01-01 00:04:38,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
271549,2015-01-01 00:04:49,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54250,2015-06-30 23:54:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75070,2015-06-30 23:55:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98213,2015-06-30 23:55:00,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97270,2015-06-30 23:55:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26382,2015-06-30 23:55:00,2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
308415,2015-06-30 23:55:00,36,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6295,2015-06-30 23:55:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
318859,2015-06-30 23:55:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
231723,2015-06-30 23:55:00,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49595,2015-06-30 23:56:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299790,2015-06-30 23:56:00,38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60864,2015-06-30 23:56:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118246,2015-06-30 23:57:00,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
199428,2015-06-30 23:57:00,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
325288,2015-06-30 23:57:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
240208,2015-06-30 23:57:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
271526,2015-06-30 23:57:00,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
422489,2015-06-30 23:57:00,77,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
300323,2015-06-30 23:57:00,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30528,2015-06-30 23:57:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72543,2015-06-30 23:58:00,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
209074,2015-06-30 23:58:00,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260595,2015-06-30 23:58:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91035,2015-06-30 23:58:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
185881,2015-06-30 23:58:00,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249267,2015-06-30 23:59:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
126105,2015-06-30 23:59:00,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
206813,2015-06-30 23:59:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18851,2015-06-30 23:59:00,22,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41611,2015-06-30 23:59:00,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
df.to_csv('locations_final_no_weather_hols.csv')

In [14]:
pd.options.display.float_format = '{:,.0f}'.format
df

,ds,y,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Willets Point,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,6_Alphabet City,6_Battery Park
77488,2015-01-01 00:00:29,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63794,2015-01-01 00:00:38,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
234906,2015-01-01 00:00:53,47,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150977,2015-01-01 00:01:08,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36702,2015-01-01 00:01:19,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5248,2015-01-01 00:01:23,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
122895,2015-01-01 00:01:32,25,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
254914,2015-01-01 00:01:34,22,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
299791,2015-01-01 00:01:37,41,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
118304,2015-01-01 00:01:41,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43880,2015-01-01 00:01:44,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
121584,2015-01-01 00:01:53,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49596,2015-01-01 00:02:12,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,2015-01-01 00:02:34,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325289,2015-01-01 00:03:03,38,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
282541,2015-01-01 00:03:03,50,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
144261,2015-01-01 00:03:16,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
430904,2015-01-01 00:03:22,35,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34829,2015-01-01 00:03:29,11,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506867,2015-01-01 00:03:33,31,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
312408,2015-01-01 00:03:43,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249818,2015-01-01 00:03:49,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
87844,2015-01-01 00:03:56,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,2015-01-01 00:03:58,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113485,2015-01-01 00:04:01,16,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10753,2015-01-01 00:04:02,18,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74819,2015-01-01 00:04:29,24,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42519,2015-01-01 00:04:35,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119695,2015-01-01 00:04:38,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
271549,2015-01-01 00:04:49,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54250,2015-06-30 23:54:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75070,2015-06-30 23:55:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98213,2015-06-30 23:55:00,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97270,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26382,2015-06-30 23:55:00,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
308415,2015-06-30 23:55:00,36,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6295,2015-06-30 23:55:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
318859,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
231723,2015-06-30 23:55:00,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49595,2015-06-30 23:56:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
299790,2015-06-30 23:56:00,38,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60864,2015-06-30 23:56:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
118246,2015-06-30 23:57:00,16,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
199428,2015-06-30 23:57:00,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325288,2015-06-30 23:57:00,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240208,2015-06-30 23:57:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
271526,2015-06-30 23:57:00,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
422489,2015-06-30 23:57:00,77,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
300323,2015-06-30 23:57:00,13,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30528,2015-06-30 23:57:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72543,2015-06-30 23:58:00,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
209074,2015-06-30 23:58:00,11,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260595,2015-06-30 23:58:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
91035,2015-06-30 23:58:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
185881,2015-06-30 23:58:00,25,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249267,2015-06-30 23:59:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
126105,2015-06-30 23:59:00,20,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206813,2015-06-30 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18851,2015-06-30 23:59:00,22,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41611,2015-06-30 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df.to_csv('locations_final_no_weather_hols.csv')

In [30]:
df.tail(7651)

,ds,y,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Willets Point,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,6_Alphabet City,6_Battery Park
515322,2015-06-30 00:00:00,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
118272,2015-06-30 00:00:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
369041,2015-06-30 00:00:00,16,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
67310,2015-06-30 00:00:00,17,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
101661,2015-06-30 00:00:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
279024,2015-06-30 00:01:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
271509,2015-06-30 00:01:00,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36691,2015-06-30 00:01:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
243477,2015-06-30 00:01:00,12,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
343831,2015-06-30 00:01:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82964,2015-06-30 00:02:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
134696,2015-06-30 00:02:00,13,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63757,2015-06-30 00:02:00,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
162209,2015-06-30 00:02:00,13,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
151368,2015-06-30 00:02:00,17,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
300279,2015-06-30 00:02:00,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
342434,2015-06-30 00:02:00,35,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323359,2015-06-30 00:02:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
354185,2015-06-30 00:03:00,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
481493,2015-06-30 00:03:00,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192380,2015-06-30 00:03:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251906,2015-06-30 00:03:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11970,2015-06-30 00:03:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75861,2015-06-30 00:04:00,9,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
288303,2015-06-30 00:04:00,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
218945,2015-06-30 00:04:00,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93968,2015-06-30 00:04:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
254892,2015-06-30 00:04:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
177100,2015-06-30 00:04:00,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
263142,2015-06-30 00:04:00,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54250,2015-06-30 23:54:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75070,2015-06-30 23:55:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98213,2015-06-30 23:55:00,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97270,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26382,2015-06-30 23:55:00,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
308415,2015-06-30 23:55:00,36,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6295,2015-06-30 23:55:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
318859,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
231723,2015-06-30 23:55:00,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49595,2015-06-30 23:56:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
299790,2015-06-30 23:56:00,38,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60864,2015-06-30 23:56:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
118246,2015-06-30 23:57:00,16,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
199428,2015-06-30 23:57:00,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325288,2015-06-30 23:57:00,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240208,2015-06-30 23:57:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
271526,2015-06-30 23:57:00,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
422489,2015-06-30 23:57:00,77,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
300323,2015-06-30 23:57:00,13,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30528,2015-06-30 23:57:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72543,2015-06-30 23:58:00,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
209074,2015-06-30 23:58:00,11,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260595,2015-06-30 23:58:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
91035,2015-06-30 23:58:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
185881,2015-06-30 23:58:00,25,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249267,2015-06-30 23:59:00,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
126105,2015-06-30 23:59:00,20,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206813,2015-06-30 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18851,2015-06-30 23:59:00,22,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41611,2015-06-30 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
df.loc[df['6_Battery Park City'] == 1]

,ds,y,6_Battery Park City,6_Bloomingdale,6_Central Harlem,6_Central Harlem North,6_Central Park,6_Chinatown,6_Clinton East,6_Clinton West,...,7_Willets Point,7_Williamsbridge/Olinville,7_Williamsburg (North Side),7_Williamsburg (South Side),7_Windsor Terrace,7_Woodhaven,7_Woodlawn/Wakefield,7_Woodside,6_Alphabet City,6_Battery Park
10333,2015-01-01 00:14:10,28,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10334,2015-01-01 00:50:38,23,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10335,2015-01-01 01:25:50,6,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10336,2015-01-01 01:57:19,8,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10337,2015-01-01 02:20:18,19,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10338,2015-01-01 02:45:06,4,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10339,2015-01-01 03:02:21,12,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10340,2015-01-01 03:49:01,11,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10341,2015-01-01 04:17:40,3,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10342,2015-01-01 04:35:30,3,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10343,2015-01-01 05:14:17,6,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10344,2015-01-01 05:32:16,4,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10345,2015-01-01 06:08:51,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10346,2015-01-01 06:59:22,3,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10347,2015-01-01 07:18:33,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10348,2015-01-01 07:37:03,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10349,2015-01-01 08:19:57,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10350,2015-01-01 08:40:23,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10351,2015-01-01 09:10:30,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10352,2015-01-01 09:46:40,3,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10353,2015-01-01 10:18:49,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10354,2015-01-01 10:40:24,2,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10355,2015-01-01 11:08:16,3,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10356,2015-01-01 11:54:17,5,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10357,2015-01-01 12:21:14,4,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10358,2015-01-01 12:55:13,7,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10359,2015-01-01 13:15:47,7,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10360,2015-01-01 13:31:15,8,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10361,2015-01-01 14:12:52,8,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10362,2015-01-01 14:51:27,9,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18822,2015-06-30 09:16:00,29,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18823,2015-06-30 09:37:00,21,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18824,2015-06-30 10:04:00,18,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18825,2015-06-30 10:53:00,13,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18826,2015-06-30 11:29:00,15,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18827,2015-06-30 11:43:00,21,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18828,2015-06-30 12:20:00,12,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18829,2015-06-30 12:56:00,19,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18830,2015-06-30 13:14:00,28,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18831,2015-06-30 13:49:00,15,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18832,2015-06-30 14:19:00,14,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18833,2015-06-30 14:53:00,22,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18834,2015-06-30 15:15:00,16,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18835,2015-06-30 15:42:00,34,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18836,2015-06-30 16:14:00,26,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18837,2015-06-30 16:55:00,30,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18838,2015-06-30 17:21:00,32,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18839,2015-06-30 17:40:00,45,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18840,2015-06-30 18:28:00,56,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18841,2015-06-30 18:34:00,41,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18842,2015-06-30 19:01:00,50,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18843,2015-06-30 19:32:00,39,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18844,2015-06-30 20:03:00,37,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18845,2015-06-30 20:57:00,28,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18846,2015-06-30 21:04:00,37,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18847,2015-06-30 21:31:00,44,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18848,2015-06-30 22:20:00,42,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18849,2015-06-30 22:59:00,23,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18850,2015-06-30 23:14:00,20,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18851,2015-06-30 23:59:00,22,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0