In [1]:
import pandas as pd
#read
df = pd.read_csv('final-2.csv')
df=df.drop(['Unnamed: 0'],axis=1)
df.tail(210000)

,ds,y,7_Allerton/Pelham Gardens,7_Bedford Park,7_Belmont,7_Bronx Park,7_Bronxdale,7_City Island,7_Claremont/Bathgate,7_Co-Op City,...,7_West Brighton,7_Westerleigh,Temperature,Humidity,Pressure,snow,Wind Direction,Wind Speed,rain,Holiday
1112691,2015-06-04 23:07:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112692,2015-06-04 23:07:00,19,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112693,2015-06-04 23:08:00,4,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112694,2015-06-04 23:08:00,2,0,0,0,0,1,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112695,2015-06-04 23:08:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112696,2015-06-04 23:08:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112697,2015-06-04 23:08:00,2,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112698,2015-06-04 23:09:00,13,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112699,2015-06-04 23:09:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112700,2015-06-04 23:09:00,29,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112701,2015-06-04 23:09:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112702,2015-06-04 23:09:00,7,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112703,2015-06-04 23:10:00,26,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112704,2015-06-04 23:10:00,79,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112705,2015-06-04 23:10:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112706,2015-06-04 23:10:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112707,2015-06-04 23:10:00,65,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112708,2015-06-04 23:10:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112709,2015-06-04 23:10:00,21,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112710,2015-06-04 23:11:00,1,1,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112711,2015-06-04 23:11:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112712,2015-06-04 23:11:00,49,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112713,2015-06-04 23:11:00,43,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112714,2015-06-04 23:11:00,2,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112715,2015-06-04 23:11:00,2,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112716,2015-06-04 23:11:00,25,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112717,2015-06-04 23:12:00,3,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112718,2015-06-04 23:12:00,4,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112719,2015-06-04 23:12:00,16,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
1112720,2015-06-04 23:12:00,1,0,0,0,0,0,0,0,0,...,0,0,289.206,66,1032,0,105,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1322661,2015-06-30 23:54:00,4,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322662,2015-06-30 23:55:00,1,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322663,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322664,2015-06-30 23:55:00,36,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322665,2015-06-30 23:55:00,1,0,0,0,0,0,0,0,0,...,1,0,297.300,69,1011,0,150,5,2,0
1322666,2015-06-30 23:55:00,5,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322667,2015-06-30 23:55:00,3,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322668,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322669,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322670,2015-06-30 23:56:00,2,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322671,2015-06-30 23:56:00,1,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322672,2015-06-30 23:56:00,38,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322673,2015-06-30 23:57:00,16,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322674,2015-06-30 23:57:00,77,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322675,2015-06-30 23:57:00,3,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322676,2015-06-30 23:57:00,4,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322677,2015-06-30 23:57:00,13,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322678,2015-06-30 23:57:00,1,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322679,2015-06-30 23:57:00,2,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322680,2015-06-30 23:57:00,6,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322681,2015-06-30 23:58:00,11,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322682,2015-06-30 23:58:00,6,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322683,2015-06-30 23:58:00,1,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322684,2015-06-30 23:58:00,2,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322685,2015-06-30 23:58:00,25,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322686,2015-06-30 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322687,2015-06-30 23:59:00,22,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322688,2015-06-30 23:59:00,20,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322689,2015-06-30 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0
1322690,2015-06-30 23:59:00,2,0,0,0,0,0,0,0,0,...,0,0,297.300,69,1011,0,150,5,2,0

In [18]:
df.tail(240522)

,ds,y,7_Allerton/Pelham Gardens,7_Bedford Park,7_Belmont,7_Bronx Park,7_Bronxdale,7_City Island,7_Claremont/Bathgate,7_Co-Op City,...,7_West Brighton,7_Westerleigh,Temperature,Humidity,Pressure,snow,Wind Direction,Wind Speed,rain,Holiday
1082169,2015-06-01 00:03:00,4,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082170,2015-06-01 00:03:00,2,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082171,2015-06-01 00:04:00,9,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082172,2015-06-01 00:04:00,1,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082173,2015-06-01 00:05:00,10,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082174,2015-06-01 00:06:00,4,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082175,2015-06-01 00:06:00,14,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082176,2015-06-01 00:06:00,1,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082177,2015-06-01 00:06:00,5,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082178,2015-06-01 00:06:00,87,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082179,2015-06-01 00:07:00,10,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082180,2015-06-01 00:07:00,6,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082181,2015-06-01 00:07:00,5,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082182,2015-06-01 00:08:00,19,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082183,2015-06-01 00:08:00,2,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082184,2015-06-01 00:08:00,4,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082185,2015-06-01 00:09:00,2,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082186,2015-06-01 00:09:00,7,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082187,2015-06-01 00:09:00,7,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082188,2015-06-01 00:09:00,3,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082189,2015-06-01 00:09:00,7,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082190,2015-06-01 00:09:00,4,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082191,2015-06-01 00:10:00,1,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082192,2015-06-01 00:10:00,2,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082193,2015-06-01 00:10:00,1,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082194,2015-06-01 00:10:00,6,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082195,2015-06-01 00:10:00,8,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082196,2015-06-01 00:10:00,2,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082197,2015-06-01 00:11:00,2,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
1082198,2015-06-01 00:11:00,15,0,0,0,0,0,0,0,0,...,0,0,292.36,83,1016,0,120,6,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1322661,2015-06-30 23:54:00,4,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322662,2015-06-30 23:55:00,1,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322663,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322664,2015-06-30 23:55:00,36,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322665,2015-06-30 23:55:00,1,0,0,0,0,0,0,0,0,...,1,0,297.30,69,1011,0,150,5,2,0
1322666,2015-06-30 23:55:00,5,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322667,2015-06-30 23:55:00,3,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322668,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322669,2015-06-30 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322670,2015-06-30 23:56:00,2,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322671,2015-06-30 23:56:00,1,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322672,2015-06-30 23:56:00,38,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322673,2015-06-30 23:57:00,16,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322674,2015-06-30 23:57:00,77,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322675,2015-06-30 23:57:00,3,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322676,2015-06-30 23:57:00,4,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322677,2015-06-30 23:57:00,13,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322678,2015-06-30 23:57:00,1,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322679,2015-06-30 23:57:00,2,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322680,2015-06-30 23:57:00,6,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322681,2015-06-30 23:58:00,11,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322682,2015-06-30 23:58:00,6,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322683,2015-06-30 23:58:00,1,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322684,2015-06-30 23:58:00,2,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322685,2015-06-30 23:58:00,25,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322686,2015-06-30 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322687,2015-06-30 23:59:00,22,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322688,2015-06-30 23:59:00,20,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322689,2015-06-30 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
1322690,2015-06-30 23:59:00,2,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0

In [3]:
from fbprophet import Prophet
#initiate
m = Prophet()

In [4]:
#add regressors
cols=list(df.columns.values)[2:]
for col in cols:
    m.add_regressor(col)

In [6]:
#divide into train,valid
train=df.loc[0:(1322691-7651-1),:]
train

,ds,y,7_Allerton/Pelham Gardens,7_Bedford Park,7_Belmont,7_Bronx Park,7_Bronxdale,7_City Island,7_Claremont/Bathgate,7_Co-Op City,...,7_Stapleton,7_West Brighton,7_Westerleigh,Temperature,Humidity,Pressure,Weather Type,Wind Direction,Wind Speed,Holiday
0,2015-01-01 00:00:29,4,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
1,2015-01-01 00:00:38,1,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
2,2015-01-01 00:00:53,47,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
3,2015-01-01 00:01:08,7,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
4,2015-01-01 00:01:19,1,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
5,2015-01-01 00:01:23,1,0,0,0,0,0,0,0,0,...,1,0,0,268.05,59,1022,sky is clear,249,2,1
6,2015-01-01 00:01:32,25,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
7,2015-01-01 00:01:34,22,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
8,2015-01-01 00:01:37,41,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
9,2015-01-01 00:01:41,7,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
10,2015-01-01 00:01:44,2,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
11,2015-01-01 00:01:53,2,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
12,2015-01-01 00:02:12,4,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
13,2015-01-01 00:02:34,1,1,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
14,2015-01-01 00:03:03,50,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
15,2015-01-01 00:03:03,38,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
16,2015-01-01 00:03:16,4,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
17,2015-01-01 00:03:22,35,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
18,2015-01-01 00:03:29,11,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
19,2015-01-01 00:03:33,31,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
20,2015-01-01 00:03:43,7,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
21,2015-01-01 00:03:49,6,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
22,2015-01-01 00:03:56,1,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
23,2015-01-01 00:03:58,5,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
24,2015-01-01 00:04:01,16,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
25,2015-01-01 00:04:02,18,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
26,2015-01-01 00:04:29,24,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
27,2015-01-01 00:04:35,2,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
28,2015-01-01 00:04:38,3,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
29,2015-01-01 00:04:49,1,0,0,0,0,0,0,0,0,...,0,0,0,268.05,59,1022,sky is clear,249,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1315010,2015-06-29 23:54:00,1,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315011,2015-06-29 23:55:00,5,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315012,2015-06-29 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315013,2015-06-29 23:55:00,2,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315014,2015-06-29 23:55:00,8,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315015,2015-06-29 23:55:00,6,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315016,2015-06-29 23:55:00,3,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315017,2015-06-29 23:55:00,3,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315018,2015-06-29 23:55:00,6,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315019,2015-06-29 23:56:00,3,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315020,2015-06-29 23:56:00,82,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315021,2015-06-29 23:56:00,9,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315022,2015-06-29 23:56:00,24,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315023,2015-06-29 23:56:00,10,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315024,2015-06-29 23:56:00,2,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315025,2015-06-29 23:56:00,32,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315026,2015-06-29 23:56:00,7,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315027,2015-06-29 23:57:00,4,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315028,2015-06-29 23:57:00,1,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315029,2015-06-29 23:57:00,42,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315030,2015-06-29 23:57:00,3,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315031,2015-06-29 23:57:00,6,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315032,2015-06-29 23:58:00,1,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315033,2015-06-29 23:58:00,1,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315034,2015-06-29 23:58:00,2,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315035,2015-06-29 23:58:00,40,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315036,2015-06-29 23:58:00,1,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315037,2015-06-29 23:59:00,6,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315038,2015-06-29 23:59:00,1,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0
1315039,2015-06-29 23:59:00,19,0,0,0,0,0,0,0,0,...,0,0,0,297.52,47,1014,sky is clear,280,3,0

In [8]:
#valid=all 7651 entries from last day, i.e. 30th June 2015
cols=list(df.columns.values)
cols.remove('y')
valid=df.loc[1315040:,cols]
valid

,ds,7_Allerton/Pelham Gardens,7_Bedford Park,7_Belmont,7_Bronx Park,7_Bronxdale,7_City Island,7_Claremont/Bathgate,7_Co-Op City,7_Country Club,...,7_Stapleton,7_West Brighton,7_Westerleigh,Temperature,Humidity,Pressure,Weather Type,Wind Direction,Wind Speed,Holiday
1315040,2015-06-30 00:00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315041,2015-06-30 00:00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315042,2015-06-30 00:00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315043,2015-06-30 00:00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315044,2015-06-30 00:00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315045,2015-06-30 00:01:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315046,2015-06-30 00:01:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315047,2015-06-30 00:01:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315048,2015-06-30 00:01:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315049,2015-06-30 00:01:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315050,2015-06-30 00:02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315051,2015-06-30 00:02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315052,2015-06-30 00:02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315053,2015-06-30 00:02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315054,2015-06-30 00:02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315055,2015-06-30 00:02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315056,2015-06-30 00:02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315057,2015-06-30 00:02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315058,2015-06-30 00:03:00,0,0,1,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315059,2015-06-30 00:03:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315060,2015-06-30 00:03:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315061,2015-06-30 00:03:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315062,2015-06-30 00:03:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315063,2015-06-30 00:04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315064,2015-06-30 00:04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315065,2015-06-30 00:04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315066,2015-06-30 00:04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315067,2015-06-30 00:04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315068,2015-06-30 00:04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
1315069,2015-06-30 00:04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,296.36,53,1013,few clouds,230,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1322661,2015-06-30 23:54:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322662,2015-06-30 23:55:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322663,2015-06-30 23:55:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322664,2015-06-30 23:55:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322665,2015-06-30 23:55:00,0,0,0,0,0,0,0,0,0,...,0,1,0,297.30,69,1011,light rain,150,5,0
1322666,2015-06-30 23:55:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322667,2015-06-30 23:55:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322668,2015-06-30 23:55:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322669,2015-06-30 23:55:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322670,2015-06-30 23:56:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322671,2015-06-30 23:56:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322672,2015-06-30 23:56:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322673,2015-06-30 23:57:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322674,2015-06-30 23:57:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322675,2015-06-30 23:57:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322676,2015-06-30 23:57:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322677,2015-06-30 23:57:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322678,2015-06-30 23:57:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322679,2015-06-30 23:57:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322680,2015-06-30 23:57:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322681,2015-06-30 23:58:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322682,2015-06-30 23:58:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322683,2015-06-30 23:58:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322684,2015-06-30 23:58:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322685,2015-06-30 23:58:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322686,2015-06-30 23:59:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322687,2015-06-30 23:59:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322688,2015-06-30 23:59:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322689,2015-06-30 23:59:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0
1322690,2015-06-30 23:59:00,0,0,0,0,0,0,0,0,0,...,0,0,0,297.30,69,1011,light rain,150,5,0

In [ ]:
#train/fit model
m.fit(train)

In [ ]:
#predict
forecast = m.predict(valid)
forecast

In [ ]:
#save predictions
forecast.to_csv('preds.csv')

In [2]:
#if saved, read
forecast = pd.read_csv('preds.csv')
forecast

,Unnamed: 0,ds,trend,trend_lower,trend_upper,yhat_lower,yhat_upper,6_Alphabet City,6_Alphabet City_lower,6_Alphabet City_upper,...,seasonalities,seasonalities_lower,seasonalities_upper,snow,snow_lower,snow_upper,weekly,weekly_lower,weekly_upper,yhat
0,0,2015-06-30 00:00:00,8.536669,8.536669,8.536669,-12.293565,16.616040,0.0,0.0,0.0,...,0.608250,0.608250,0.608250,-0.014071,-0.014071,-0.014071,-1.724883,-1.724883,-1.724883,2.575003
1,1,2015-06-30 00:00:00,8.536669,8.536669,8.536669,3.847778,32.981968,0.0,0.0,0.0,...,0.608250,0.608250,0.608250,-0.014071,-0.014071,-0.014071,-1.724883,-1.724883,-1.724883,18.261268
2,2,2015-06-30 00:00:00,8.536669,8.536669,8.536669,17.640618,46.403799,0.0,0.0,0.0,...,0.608250,0.608250,0.608250,-0.014071,-0.014071,-0.014071,-1.724883,-1.724883,-1.724883,32.347479
3,3,2015-06-30 00:00:00,8.536669,8.536669,8.536669,3.960339,34.869730,0.0,0.0,0.0,...,0.608250,0.608250,0.608250,-0.014071,-0.014071,-0.014071,-1.724883,-1.724883,-1.724883,19.030917
4,4,2015-06-30 00:00:00,8.536669,8.536669,8.536669,-12.818581,17.009673,0.0,0.0,0.0,...,0.608250,0.608250,0.608250,-0.014071,-0.014071,-0.014071,-1.724883,-1.724883,-1.724883,2.806105
5,5,2015-06-30 00:01:00,8.536684,8.536684,8.536684,-10.934951,17.454302,0.0,0.0,0.0,...,0.564209,0.564209,0.564209,-0.014071,-0.014071,-0.014071,-1.723615,-1.723615,-1.723615,2.681994
6,6,2015-06-30 00:01:00,8.536684,8.536684,8.536684,-10.015355,19.691076,0.0,0.0,0.0,...,0.564209,0.564209,0.564209,-0.014071,-0.014071,-0.014071,-1.723615,-1.723615,-1.723615,4.268613
7,7,2015-06-30 00:01:00,8.536684,8.536684,8.536684,-10.594090,17.657561,0.0,0.0,0.0,...,0.564209,0.564209,0.564209,-0.014071,-0.014071,-0.014071,-1.723615,-1.723615,-1.723615,3.316621
8,8,2015-06-30 00:01:00,8.536684,8.536684,8.536684,-11.601939,19.901193,0.0,0.0,0.0,...,0.564209,0.564209,0.564209,-0.014071,-0.014071,-0.014071,-1.723615,-1.723615,-1.723615,3.993299
9,9,2015-06-30 00:01:00,8.536684,8.536684,8.536684,2.932573,33.191392,0.0,0.0,0.0,...,0.564209,0.564209,0.564209,-0.014071,-0.014071,-0.014071,-1.723615,-1.723615,-1.723615,18.554648
10,10,2015-06-30 00:02:00,8.536699,8.536699,8.536699,-10.915383,18.852223,0.0,0.0,0.0,...,0.519874,0.519874,0.519874,-0.014071,-0.014071,-0.014071,-1.722347,-1.722347,-1.722347,3.586070
11,11,2015-06-30 00:02:00,8.536699,8.536699,8.536699,-6.732135,22.452885,0.0,0.0,0.0,...,0.519874,0.519874,0.519874,-0.014071,-0.014071,-0.014071,-1.722347,-1.722347,-1.722347,8.918606
12,12,2015-06-30 00:02:00,8.536699,8.536699,8.536699,24.076782,53.036325,0.0,0.0,0.0,...,0.519874,0.519874,0.519874,-0.014071,-0.014071,-0.014071,-1.722347,-1.722347,-1.722347,38.820257
13,13,2015-06-30 00:02:00,8.536699,8.536699,8.536699,-11.838720,18.637735,0.0,0.0,0.0,...,0.519874,0.519874,0.519874,-0.014071,-0.014071,-0.014071,-1.722347,-1.722347,-1.722347,2.733234
14,14,2015-06-30 00:02:00,8.536699,8.536699,8.536699,-7.430241,22.771619,0.0,0.0,0.0,...,0.519874,0.519874,0.519874,-0.014071,-0.014071,-0.014071,-1.722347,-1.722347,-1.722347,7.377663
15,15,2015-06-30 00:02:00,8.536699,8.536699,8.536699,10.737005,41.272767,0.0,0.0,0.0,...,0.519874,0.519874,0.519874,-0.014071,-0.014071,-0.014071,-1.722347,-1.722347,-1.722347,25.344423
16,16,2015-06-30 00:02:00,8.536699,8.536699,8.536699,-2.804728,26.732556,0.0,0.0,0.0,...,0.519874,0.519874,0.519874,-0.014071,-0.014071,-0.014071,-1.722347,-1.722347,-1.722347,12.046386
17,17,2015-06-30 00:02:00,8.536699,8.536699,8.536699,12.496078,43.746163,0.0,0.0,0.0,...,0.519874,0.519874,0.519874,-0.014071,-0.014071,-0.014071,-1.722347,-1.722347,-1.722347,28.639912
18,18,2015-06-30 00:03:00,8.536715,8.536715,8.536715,-11.972323,17.515966,0.0,0.0,0.0,...,0.475247,0.475247,0.475247,-0.014071,-0.014071,-0.014071,-1.721079,-1.721079,-1.721079,2.955305
19,19,2015-06-30 00:03:00,8.536715,8.536715,8.536715,19.226396,48.803298,0.0,0.0,0.0,...,0.475247,0.475247,0.475247,-0.014071,-0.014071,-0.014071,-1.721079,-1.721079,-1.721079,34.835335
20,20,2015-06-30 00:03:00,8.536715,8.536715,8.536715,-10.234011,18.660969,0.0,0.0,0.0,...,0.475247,0.475247,0.475247,-0.014071,-0.014071,-0.014071,-1.721079,-1.721079,-1.721079,4.162998
21,21,2015-06-30 00:03:00,8.536715,8.536715,8.536715,-6.936248,22.500920,0.0,0.0,0.0,...,0.475247,0.475247,0.475247,-0.014071,-0.014071,-0.014071,-1.721079,-1.721079,-1.721079,8.320212
22,22,2015-06-30 00:03:00,8.536715,8.536715,8.536715,-12.281816,17.991734,0.0,0.0,0.0,...,0.475247,0.475247,0.475247,-0.014071,-0.014071,-0.014071,-1.721079,-1.721079,-1.721079,3.105423
23,23,2015-06-30 00:04:00,8.536730,8.536730,8.536730,-8.634307,21.295540,0.0,0.0,0.0,...,0.430327,0.430327,0.430327,-0.014071,-0.014071,-0.014071,-1.719811,-1.719811,-1.719811,6.452540
24,24,2015-06-30 00:04:00,8.536730,8.536730,8.536730,5.605608,35.451520,0.0,0.0,0.0,...,0.430327,0.430327,0.430327,-0.014071,-0.014071,-0.014071,-1.719811,-1.719811,-1.719811,19.851393
25,25,2015-06-30 00:04:00,8.536730,8.536730,8.536730,10.951544,40.895014,0.0,0.0,0.0,...,0.430327,0.430327,0.430327,-0.014071,-0.014071,-0.014071,-1.719811,-1.719811,-1.719811,25.503706
26,26,2015-06-30 00:04:00,8.536730,8.536730,8.536730,-11.030038,19.754977,0.0,0.0,0.0,...,0.430327,0.430327,0.430327,-0.014071,-0.014071,-0.014071,-1.719811,-1.719811,-1.719811,4.863243
27,27,2015-06-30 00:04:00,8.536730,8.536730,8.536730,-11.309495,17.299641,0.0,0.0,0.0,...,0.430327,0.430327,0.430327,-0.014071,-0.014071,-0.014071,-1.719811,-1.719811,-1.719811,2.831532
28,28,2015-06-30 00:04:00,8.536730,8.536730,8.536730,-14.012576,15.753083,0.0,0.0,0.0,...,0.430327,0.430327,0.430327,-0.014071,-0.014071,-0.014071,-1.719811,-1.719811,-1.719811,1.568687
29,29,2015-06-30 00:04:00,8.536730,8.536730,8.536730,-6.584754,22.644476,0.0,0.0,0.0,...,0.430327,0.430327,0.430327,-0.014071,-0.014071,-0.014071,-1.719811,-1.719811,-1.719811,7.967339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7621,7621,2015-06-30 23:54:00,8.558677,8.558677,8.558677,-10.024384,20.274957,0.0,0.0,0.0,...,1.818324,1.818324,1.818324,-0.014071,-0.014071,-0.014071,-0.780474,-0.780474,-0.780474,4.326588
7622,7622,2015-06-30 23:55:00,8.558693,8.558693,8.558693,-8.941112,21.395631,0.0,0.0,0.0,...,1.774903,1.774903,1.774903,-0.014071,-0.014071,-0.014071,-0.780356,-0.780356,-0.780356,6.763786
7623,7623,2015-06-30 23:55:00,8.558693,8.558693,8.558693,-6.235040,25.071338,0.0,0.0,0.0,...,1.774903,1.774903,1.774903,-0.014071,-0.014071,-0.014071,-0.780356,-0.780356,-0.780356,9.039617
7624,7624,2015-06-30 23:55:00,8.558693,8.558693,8.558693,-10.774406,18.900194,0.0,0.0,0.0,...,1.774903,1.774903,1.774903,-0.014071,-0.014071,-0.014071,-0.780356,-0.780356,-0.780356,4.397345
7625,7625,2015-06-30 23:55:00,8.558693,8.558693,8.558693,-4.964391,23.663956,0.0,0.0,0.0,...,1.774903,1.774903,1.774903,-0.014071,-0.014071,-0.014071,-0.780356,-0.780356,-0.780356,8.408421
7626,7626,2015-06-30 23:55:00,8.558693,8.558693,8.558693,-10.802566,19.301828,0.0,0.0,0.0,...,1.774903,1.774903,1.774903,-0.014071,-0.014071,-0.014071,-0.780356,-0.780356,-0.780356,4.091047
7627,7627,2015-06-30 23:55:00,8.558693,8.558693,8.558693,22.033026,53.515971,0.0,0.0,0.0,...,1.774903,1.774903,1.774903,-0.014071,-0.014071,-0.014071,-0.780356,-0.780356,-0.780356,38.513526
7628,7628,2015-06-30 23:55:00,8.558693,8.558693,8.558693,-8.516733,21.279035,0.0,0.0,0.0,...,1.774903,1.774903,1.774903,-0.014071,-0.014071,-0.014071,-0.780356,-0.780356,-0.780356,6.276513
7629,7629,2015-06-30 23:55:00,8.558693,8.558693,8.558693,-11.830051,17.773215,0.0,0.0,0.0,...,1.774903,1.774903,1.774903,-0.014071,-0.014071,-0.014071,-0.780356,-0.780356,-0.780356,3.588018
7630,7630,2015-06-30 23:56:00,8.558708,8.558708,8.558708,-10.317238,20.896689,0.0,0.0,0.0,...,1.731187,1.731187,1.731187,-0.014071,-0.014071,-0.014071,-0.780237,-0.780237,-0.780237,5.278527
7631,7631,2015-06-30 23:56:00,8.558708,8.558708,8.558708,-10.483688,19.242889,0.0,0.0,0.0,...,1.731187,1.731187,1.731187,-0.014071,-0.014071,-0.014071,-0.780237,-0.780237,-0.780237,4.287729
7632,7632,2015-06-30 23:56:00,8.558708,8.558708,8.558708,22.280015,52.876782,0.0,0.0,0.0,...,1.731187,1.731187,1.731187,-0.014071,-0.014071,-0.014071,-0.780237,-0.780237,-0.780237,37.176287
7633,7633,2015-06-30 23:57:00,8.558723,8.558723,8.558723,-7.512309,21.707834,0.0,0.0,0.0,...,1.687175,1.687175,1.687175,-0.014071,-0.014071,-0.014071,-0.780119,-0.780119,-0.780119,7.204584
7634,7634,2015-06-30 23:57:00,8.558723,8.558723,8.558723,-10.051465,18.982220,0.0,0.0,0.0,...,1.687175,1.687175,1.687175,-0.014071,-0.014071,-0.014071,-0.780119,-0.780119,-0.780119,4.345199
7635,7635,2015-06-30 23:57:00,8.558723,8.558723,8.558723,-10.435614,19.672340,0.0,0.0,0.0,...,1.687175,1.687175,1.687175,-0.014071,-0.014071,-0.014071,-0.780119,-0.780119,-0.780119,4.718866
7636,7636,2015-06-30 23:57:00,8.558723,8.558723,8.558723,-4.940398,24.253272,0.0,0.0,0.0,...,1.687175,1.687175,1.687175,-0.014071,-0.014071,-0.014071,-0.780119,-0.780119,-0.780119,10.418424
7637,7637,2015-06-30 23:57:00,8.558723,8.558723,8.558723,-4.216900,23.782739,0.0,0.0,0.0,...,1.687175,1.687175,1.687175,-0.014071,-0.014071,-0.014071,-0.780119,-0.780119,-0.780119,10.605662
7638,7638,2015-06-30 23:57:00,8.558723,8.558723,8.558723,36.896224,67.020580,0.0,0.0,0.0,...,1.687175,1.687175,1.687175,-0.014071,-0.014071,-0.014071,-0.780119,-0.780119,-0.780119,52.525933
7639,7639,2015-06-30 23:57:00,8.558723,8.558723,8.558723,6.868214,37.625400,0.0,0.0,0.0,...,1.687175,1.687175,1.687175,-0.014071,-0.014071,-0.014071,-0.780119,-0.780119,-0.780119,22.040887
7640,7640,2015-06-30 23:57:00,8.558723,8.558723,8.558723,-4.710064,26.483526,0.0,0.0,0.0,...,1.687175,1.687175,1.687175,-0.014071,-0.014071,-0.014071,-0.780119,-0.780119,-0.780119,10.489707
7641,7641,2015-06-30 23:58:00,8.558739,8.558739,8.558739,3.369001,33.847730,0.0,0.0,0.0,...,1.642868,1.642868,1.642868,-0.014071,-0.014071,-0.014071,-0.780000,-0.780000,-0.780000,18.821151
7642,7642,2015-06-30 23:58:00,8.558739,8.558739,8.558739,-5.839898,24.785142,0.0,0.0,0.0,...,1.642868,1.642868,1.642868,-0.014071,-0.014071,-0.014071,-0.780000,-0.780000,-0.780000,9.362655
7643,7643,2015-06-30 23:58:00,8.558739,8.558739,8.558739,-8.002350,21.641972,0.0,0.0,0.0,...,1.642868,1.642868,1.642868,-0.014071,-0.014071,-0.014071,-0.780000,-0.780000,-0.780000,6.018639
7644,7644,2015-06-30 23:58:00,8.558739,8.558739,8.558739,-10.671180,18.172597,0.0,0.0,0.0,...,1.642868,1.642868,1.642868,-0.014071,-0.014071,-0.014071,-0.780000,-0.780000,-0.780000,4.232683
7645,7645,2015-06-30 23:58:00,8.558739,8.558739,8.558739,-9.893692,18.667162,0.0,0.0,0.0,...,1.642868,1.642868,1.642868,-0.014071,-0.014071,-0.014071,-0.780000,-0.780000,-0.780000,4.031069
7646,7646,2015-06-30 23:59:00,8.558754,8.558754,8.558754,-4.209704,25.930904,0.0,0.0,0.0,...,1.598266,1.598266,1.598266,-0.014071,-0.014071,-0.014071,-0.779882,-0.779882,-0.779882,10.788389
7647,7647,2015-06-30 23:59:00,8.558754,8.558754,8.558754,-10.609399,18.779527,0.0,0.0,0.0,...,1.598266,1.598266,1.598266,-0.014071,-0.014071,-0.014071,-0.779882,-0.779882,-0.779882,4.252238
7648,7648,2015-06-30 23:59:00,8.558754,8.558754,8.558754,-9.785235,19.964378,0.0,0.0,0.0,...,1.598266,1.598266,1.598266,-0.014071,-0.014071,-0.014071,-0.779882,-0.779882,-0.779882,4.765342
7649,7649,2015-06-30 23:59:00,8.558754,8.558754,8.558754,5.253404,35.160594,0.0,0.0,0.0,...,1.598266,1.598266,1.598266,-0.014071,-0.014071,-0.014071,-0.779882,-0.779882,-0.779882,20.277500
7650,7650,2015-06-30 23:59:00,8.558754,8.558754,8.558754,-9.510802,20.148062,0.0,0.0,0.0,...,1.598266,1.598266,1.598266,-0.014071,-0.014071,-0.014071,-0.779882,-0.779882,-0.779882,5.102937

In [10]:
forecast.loc[forecast['6_Alphabet City'] != 0.0]

,Unnamed: 0,ds,trend,trend_lower,trend_upper,yhat_lower,yhat_upper,6_Alphabet City,6_Alphabet City_lower,6_Alphabet City_upper,...,seasonalities,seasonalities_lower,seasonalities_upper,snow,snow_lower,snow_upper,weekly,weekly_lower,weekly_upper,yhat
103,103,2015-06-30 00:17:00,8.536929,8.536929,8.536929,-2.842630,26.580980,4.307531,4.307531,4.307531,...,-0.179854,-0.179854,-0.179854,-0.014071,-0.014071,-0.014071,-1.703343,-1.703343,-1.703343,12.255249
224,224,2015-06-30 00:42:00,8.537313,8.537313,8.537313,-4.127982,25.701636,4.307531,4.307531,4.307531,...,-1.481510,-1.481510,-1.481510,-0.014071,-0.014071,-0.014071,-1.671758,-1.671758,-1.671758,10.953976
429,429,2015-06-30 01:28:00,8.538019,8.538019,8.538019,-5.492672,23.616504,4.307531,4.307531,4.307531,...,-4.196979,-4.196979,-4.196979,-0.014071,-0.014071,-0.014071,-1.614080,-1.614080,-1.614080,8.218999
444,444,2015-06-30 01:30:00,8.538050,8.538050,8.538050,-6.284106,22.917605,4.307531,4.307531,4.307531,...,-4.319981,-4.319981,-4.319981,-0.014071,-0.014071,-0.014071,-1.611589,-1.611589,-1.611589,8.096028
708,708,2015-06-30 02:40:00,8.539124,8.539124,8.539124,-10.315873,18.984291,4.307531,4.307531,4.307531,...,-8.358149,-8.358149,-8.358149,-0.014071,-0.014071,-0.014071,-1.525539,-1.525539,-1.525539,4.127887
934,934,2015-06-30 03:43:00,8.540091,8.540091,8.540091,-13.479362,16.770446,4.307531,4.307531,4.307531,...,-10.494952,-10.494952,-10.494952,-0.014071,-0.014071,-0.014071,-1.450507,-1.450507,-1.450507,1.903990
1036,1036,2015-06-30 04:16:00,8.540598,8.540598,8.540598,-14.104583,17.728415,4.307531,4.307531,4.307531,...,-10.690957,-10.690957,-10.690957,-0.014071,-0.014071,-0.014071,-1.412335,-1.412335,-1.412335,1.738700
1144,1144,2015-06-30 04:39:00,8.540951,8.540951,8.540951,-13.227476,17.332212,4.307531,4.307531,4.307531,...,-10.428590,-10.428590,-10.428590,-0.014071,-0.014071,-0.014071,-1.386248,-1.386248,-1.386248,2.001421
1320,1320,2015-06-30 05:19:00,8.541565,8.541565,8.541565,-12.304077,18.956292,4.307531,4.307531,4.307531,...,-9.285648,-9.285648,-9.285648,-0.014071,-0.014071,-0.014071,-1.341975,-1.341975,-1.341975,3.153957
1383,1383,2015-06-30 05:37:00,8.541841,8.541841,8.541841,-11.026983,18.215456,4.307531,4.307531,4.307531,...,-8.548347,-8.548347,-8.548347,-0.014071,-0.014071,-0.014071,-1.322533,-1.322533,-1.322533,3.891535
1622,1622,2015-06-30 06:26:00,8.542593,8.542593,8.542593,-9.129379,21.110443,4.307531,4.307531,4.307531,...,-6.181219,-6.181219,-6.181219,-0.014071,-0.014071,-0.014071,-1.271221,-1.271221,-1.271221,6.437455
1674,1674,2015-06-30 06:35:00,8.542731,8.542731,8.542731,-7.863939,22.014914,4.307531,4.307531,4.307531,...,-5.730858,-5.730858,-5.730858,-0.014071,-0.014071,-0.014071,-1.262063,-1.262063,-1.262063,6.887954
1856,1856,2015-06-30 07:14:00,8.543330,8.543330,8.543330,-6.161114,23.823234,4.307531,4.307531,4.307531,...,-3.899652,-3.899652,-3.899652,-0.014071,-0.014071,-0.014071,-1.223381,-1.223381,-1.223381,8.543446
2032,2032,2015-06-30 07:43:00,8.543775,8.543775,8.543775,-3.545602,25.554341,4.307531,4.307531,4.307531,...,-2.778429,-2.778429,-2.778429,-0.014071,-0.014071,-0.014071,-1.195702,-1.195702,-1.195702,9.665114
2293,2293,2015-06-30 08:25:00,8.544419,8.544419,8.544419,-3.285543,25.711483,4.307531,4.307531,4.307531,...,-1.664855,-1.664855,-1.664855,-0.014071,-0.014071,-0.014071,-1.157316,-1.157316,-1.157316,10.849072
2460,2460,2015-06-30 08:52:00,8.544834,8.544834,8.544834,-4.137150,25.535678,4.307531,4.307531,4.307531,...,-1.282511,-1.282511,-1.282511,-0.014071,-0.014071,-0.014071,-1.133727,-1.133727,-1.133727,11.231831
2655,2655,2015-06-30 09:26:00,8.545355,8.545355,8.545355,-2.339357,26.305351,4.307531,4.307531,4.307531,...,-1.124476,-1.124476,-1.124476,-0.014071,-0.014071,-0.014071,-1.105260,-1.105260,-1.105260,11.299511
2792,2792,2015-06-30 09:49:00,8.545708,8.545708,8.545708,-3.011084,26.946689,4.307531,4.307531,4.307531,...,-1.175178,-1.175178,-1.175178,-0.014071,-0.014071,-0.014071,-1.086794,-1.086794,-1.086794,11.249162
2988,2988,2015-06-30 10:22:00,8.546215,8.546215,8.546215,-3.948202,26.238120,4.307531,4.307531,4.307531,...,-1.385526,-1.385526,-1.385526,-0.014071,-0.014071,-0.014071,-1.061425,-1.061425,-1.061425,11.139417
3042,3042,2015-06-30 10:34:00,8.546399,8.546399,8.546399,-4.566757,25.478905,4.307531,4.307531,4.307531,...,-1.483455,-1.483455,-1.483455,-0.014071,-0.014071,-0.014071,-1.052530,-1.052530,-1.052530,11.041672
3320,3320,2015-06-30 11:23:00,8.547151,8.547151,8.547151,-4.358221,24.413649,4.307531,4.307531,4.307531,...,-1.877135,-1.877135,-1.877135,-0.014071,-0.014071,-0.014071,-1.018036,-1.018036,-1.018036,10.640464
3394,3394,2015-06-30 11:35:00,8.547335,8.547335,8.547335,-4.773337,26.090636,4.307531,4.307531,4.307531,...,-1.953164,-1.953164,-1.953164,-0.014071,-0.014071,-0.014071,-1.010035,-1.010035,-1.010035,10.564620
3557,3557,2015-06-30 12:04:00,8.547780,8.547780,8.547780,-3.321931,24.922318,4.307531,4.307531,4.307531,...,-2.076294,-2.076294,-2.076294,-0.014071,-0.014071,-0.014071,-0.991423,-0.991423,-0.991423,10.253436
3841,3841,2015-06-30 12:55:00,8.548563,8.548563,8.548563,-5.229899,25.559333,4.307531,4.307531,4.307531,...,-2.030963,-2.030963,-2.030963,-0.014071,-0.014071,-0.014071,-0.961142,-0.961142,-0.961142,10.299549
3876,3876,2015-06-30 13:01:00,8.548655,8.548655,8.548655,-3.177669,24.856963,4.307531,4.307531,4.307531,...,-2.001106,-2.001106,-2.001106,-0.014071,-0.014071,-0.014071,-0.957782,-0.957782,-0.957782,10.446037
4126,4126,2015-06-30 13:47:00,8.549361,8.549361,8.549361,-3.728905,24.456190,4.307531,4.307531,4.307531,...,-1.590463,-1.590463,-1.590463,-0.014071,-0.014071,-0.014071,-0.933414,-0.933414,-0.933414,10.857385
4245,4245,2015-06-30 14:08:00,8.549683,8.549683,8.549683,-3.133992,26.420295,4.307531,4.307531,4.307531,...,-1.294487,-1.294487,-1.294487,-0.014071,-0.014071,-0.014071,-0.923092,-0.923092,-0.923092,11.287690
4431,4431,2015-06-30 14:41:00,8.550190,8.550190,8.550190,-1.259601,26.687036,4.307531,4.307531,4.307531,...,-0.693214,-0.693214,-0.693214,-0.014071,-0.014071,-0.014071,-0.907859,-0.907859,-0.907859,11.889469
4584,4584,2015-06-30 15:10:00,8.550635,8.550635,8.550635,-1.366638,28.452914,4.307531,4.307531,4.307531,...,-0.034961,-0.034961,-0.034961,-0.014071,-0.014071,-0.014071,-0.895441,-0.895441,-0.895441,12.627489
4788,4788,2015-06-30 15:44:00,8.551157,8.551157,8.551157,-1.673550,28.452340,4.307531,4.307531,4.307531,...,0.868321,0.868321,0.868321,-0.014071,-0.014071,-0.014071,-0.881993,-0.881993,-0.881993,13.531292
4948,4948,2015-06-30 16:12:00,8.551587,8.551587,8.551587,0.626760,27.804488,4.307531,4.307531,4.307531,...,1.688035,1.688035,1.688035,-0.014071,-0.014071,-0.014071,-0.871783,-0.871783,-0.871783,14.230171
5123,5123,2015-06-30 16:43:00,8.552062,8.552062,8.552062,-0.056451,29.780442,4.307531,4.307531,4.307531,...,2.628567,2.628567,2.628567,-0.014071,-0.014071,-0.014071,-0.861347,-0.861347,-0.861347,15.171179
5316,5316,2015-06-30 17:17:00,8.552584,8.552584,8.552584,1.039551,30.591911,4.307531,4.307531,4.307531,...,3.631055,3.631055,3.631055,-0.014071,-0.014071,-0.014071,-0.850896,-0.850896,-0.850896,16.258063
5415,5415,2015-06-30 17:33:00,8.552830,8.552830,8.552830,1.773538,30.979598,4.307531,4.307531,4.307531,...,4.069587,4.069587,4.069587,-0.014071,-0.014071,-0.014071,-0.846320,-0.846320,-0.846320,16.696840
5727,5727,2015-06-30 18:26:00,8.553643,8.553643,8.553643,3.116467,33.112427,4.307531,4.307531,4.307531,...,5.255389,5.255389,5.255389,-0.014071,-0.014071,-0.014071,-0.832610,-0.832610,-0.832610,18.050387
5885,5885,2015-06-30 18:52:00,8.554042,8.554042,8.554042,3.844622,32.947955,4.307531,4.307531,4.307531,...,5.647001,5.647001,5.647001,-0.014071,-0.014071,-0.014071,-0.826638,-0.826638,-0.826638,18.442398
6065,6065,2015-06-30 19:22:00,8.554503,8.554503,8.554503,3.854331,34.939989,4.307531,4.307531,4.307531,...,5.928825,5.928825,5.928825,-0.014071,-0.014071,-0.014071,-0.820303,-0.820303,-0.820303,18.550759
6252,6252,2015-06-30 19:56:00,8.555025,8.555025,8.555025,3.342821,33.799190,4.307531,4.307531,4.307531,...,6.039881,6.039881,6.039881,-0.014071,-0.014071,-0.014071,-0.813776,-0.813776,-0.813776,18.662338
6384,6384,2015-06-30 20:18:00,8.555362,8.555362,8.555362,3.053085,32.445947,4.307531,4.307531,4.307531,...,6.007998,6.007998,6.007998,-0.014071,-0.014071,-0.014071,-0.809886,-0.809886,-0.809886,18.549709
6568,6568,2015-06-30 20:51:00,8.555869,8.555869,8.555869,3.123099,33.407531,4.307531,4.307531,4.307531,...,5.832139,5.832139,5.832139,-0.014071,-0.014071,-0.014071,-0.804484,-0.804484,-0.804484,18.374357
6642,6642,2015-06-30 21:06:00,8.556099,8.556099,8.556099,3.438461,33.396804,4.307531,4.307531,4.307531,...,5.707343,5.707343,5.707343,-0.014071,-0.014071,-0.014071,-0.802182,-0.802182,-0.802182,18.228431
6804,6804,2015-06-30 21:32:00,8.556498,8.556498,8.556498,3.083441,33.538329,4.307531,4.307531,4.307531,...,5.428009,5.428009,5.428009,-0.014071,-0.014071,-0.014071,-0.798389,-0.798389,-0.798389,17.949497
7060,7060,2015-06-30 22:17:00,8.557189,8.557189,8.557189,3.111392,32.999557,4.307531,4.307531,4.307531,...,4.733801,4.733801,4.733801,-0.014071,-0.014071,-0.014071,-0.792317,-0.792317,-0.792317,17.503144
7225,7225,2015-06-30 22:45:00,8.557618,8.557618,8.557618,3.057016,32.961053,4.307531,4.307531,4.307531,...,4.128196,4.128196,4.128196,-0.014071,-0.014071,-0.014071,-0.788776,-0.788776,-0.788776,16.897968
7390,7390,2015-06-30 23:14:00,8.558063,8.558063,8.558063,1.242172,30.626274,4.307531,4.307531,4.307531,...,3.315173,3.315173,3.315173,-0.014071,-0.014071,-0.014071,-0.785239,-0.785239,-0.785239,16.081903
7552,7552,2015-06-30 23:42:00,8.558493,8.558493,8.558493,0.514707,29.906898,4.307531,4.307531,4.307531,...,2.316267,2.316267,2.316267,-0.014071,-0.014071,-0.014071,-0.781897,-0.781897,-0.781897,15.083427

In [12]:
df2 = df.tail(7651)
df2 = df2.reset_index(drop=True)

In [13]:
df2.loc[df2['6_Alphabet City'] != 0.0]

,ds,y,7_Allerton/Pelham Gardens,7_Bedford Park,7_Belmont,7_Bronx Park,7_Bronxdale,7_City Island,7_Claremont/Bathgate,7_Co-Op City,...,7_West Brighton,7_Westerleigh,Temperature,Humidity,Pressure,snow,Wind Direction,Wind Speed,rain,Holiday
100,2015-06-30 00:17:00,7,0,0,0,0,0,0,0,0,...,0,0,296.36,53,1013,0,230,2,0,0
222,2015-06-30 00:42:00,5,0,0,0,0,0,0,0,0,...,0,0,296.36,53,1013,0,230,2,0,0
426,2015-06-30 01:28:00,2,0,0,0,0,0,0,0,0,...,0,0,295.14,60,1014,0,210,1,0,0
450,2015-06-30 01:30:00,4,0,0,0,0,0,0,0,0,...,0,0,295.14,60,1014,0,210,1,0,0
709,2015-06-30 02:40:00,2,0,0,0,0,0,0,0,0,...,0,0,293.30,60,1015,0,190,1,0,0
934,2015-06-30 03:43:00,2,0,0,0,0,0,0,0,0,...,0,0,292.44,93,1009,0,259,2,0,0
1036,2015-06-30 04:16:00,2,0,0,0,0,0,0,0,0,...,0,0,291.98,82,1014,0,259,2,0,0
1144,2015-06-30 04:39:00,2,0,0,0,0,0,0,0,0,...,0,0,291.98,82,1014,0,259,2,0,0
1320,2015-06-30 05:19:00,7,0,0,0,0,0,0,0,0,...,0,0,291.57,87,1014,0,205,1,0,0
1383,2015-06-30 05:37:00,5,0,0,0,0,0,0,0,0,...,0,0,291.57,87,1014,0,205,1,0,0
1620,2015-06-30 06:26:00,6,0,0,0,0,0,0,0,0,...,0,0,291.51,93,1008,0,190,4,0,0
1673,2015-06-30 06:35:00,12,0,0,0,0,0,0,0,0,...,0,0,291.51,93,1008,0,190,4,0,0
1865,2015-06-30 07:14:00,17,0,0,0,0,0,0,0,0,...,0,0,291.40,87,1015,0,205,1,0,0
2035,2015-06-30 07:43:00,26,0,0,0,0,0,0,0,0,...,0,0,291.40,87,1015,0,205,1,0,0
2295,2015-06-30 08:25:00,24,0,0,0,0,0,0,0,0,...,0,0,290.73,87,1015,0,162,1,0,0
2453,2015-06-30 08:52:00,21,0,0,0,0,0,0,0,0,...,0,0,290.73,87,1015,0,162,1,0,0
2655,2015-06-30 09:26:00,22,0,0,0,0,0,0,0,0,...,0,0,290.29,93,1008,0,290,2,0,0
2792,2015-06-30 09:49:00,17,0,0,0,0,0,0,0,0,...,0,0,290.29,93,1008,0,290,2,0,0
2987,2015-06-30 10:22:00,15,0,0,0,0,0,0,0,0,...,0,0,290.37,87,1015,0,162,1,0,0
3045,2015-06-30 10:34:00,9,0,0,0,0,0,0,0,0,...,0,0,290.37,87,1015,0,162,1,0,0
3323,2015-06-30 11:23:00,9,0,0,0,0,0,0,0,0,...,0,0,290.82,88,1015,0,157,1,0,0
3395,2015-06-30 11:35:00,10,0,0,0,0,0,0,0,0,...,0,0,290.82,88,1015,0,157,1,0,0
3555,2015-06-30 12:04:00,9,0,0,0,0,0,0,0,0,...,0,0,292.84,93,1009,0,270,1,0,0
3843,2015-06-30 12:55:00,16,0,0,0,0,0,0,0,0,...,0,0,292.84,93,1009,0,270,1,0,0
3874,2015-06-30 13:01:00,6,0,0,0,0,0,0,0,0,...,0,0,294.19,83,1015,0,157,1,0,0
4123,2015-06-30 13:47:00,11,0,0,0,0,0,0,0,0,...,0,0,294.19,83,1015,0,157,1,0,0
4244,2015-06-30 14:08:00,7,0,0,0,0,0,0,0,0,...,0,0,296.33,53,1015,0,160,3,0,0
4426,2015-06-30 14:41:00,16,0,0,0,0,0,0,0,0,...,0,0,296.33,53,1015,0,160,3,0,0
4584,2015-06-30 15:10:00,11,0,0,0,0,0,0,0,0,...,0,0,298.06,47,1015,0,160,5,0,0
4788,2015-06-30 15:44:00,11,0,0,0,0,0,0,0,0,...,0,0,298.06,47,1015,0,160,5,0,0
4948,2015-06-30 16:12:00,8,0,0,0,0,0,0,0,0,...,0,0,299.39,57,1014,0,210,5,0,0
5121,2015-06-30 16:43:00,15,0,0,0,0,0,0,0,0,...,0,0,299.39,57,1014,0,210,5,0,0
5321,2015-06-30 17:17:00,8,0,0,0,0,0,0,0,0,...,0,0,299.52,47,1015,0,160,5,0,0
5418,2015-06-30 17:33:00,6,0,0,0,0,0,0,0,0,...,0,0,299.52,47,1015,0,160,5,0,0
5726,2015-06-30 18:26:00,6,0,0,0,0,0,0,0,0,...,0,0,299.81,51,1014,0,150,6,2,0
5885,2015-06-30 18:52:00,16,0,0,0,0,0,0,0,0,...,0,0,299.81,51,1014,0,150,6,2,0
6065,2015-06-30 19:22:00,16,0,0,0,0,0,0,0,0,...,0,0,300.13,51,1012,0,150,5,0,0
6252,2015-06-30 19:56:00,12,0,0,0,0,0,0,0,0,...,0,0,300.13,51,1012,0,150,5,0,0
6384,2015-06-30 20:18:00,8,0,0,0,0,0,0,0,0,...,0,0,299.45,54,1012,0,180,4,0,0
6567,2015-06-30 20:51:00,7,0,0,0,0,0,0,0,0,...,0,0,299.45,54,1012,0,180,4,0,0
6642,2015-06-30 21:06:00,24,0,0,0,0,0,0,0,0,...,0,0,299.02,51,1012,0,170,3,0,0
6803,2015-06-30 21:32:00,20,0,0,0,0,0,0,0,0,...,0,0,299.02,51,1012,0,170,3,0,0
7060,2015-06-30 22:17:00,13,0,0,0,0,0,0,0,0,...,0,0,298.06,61,1011,0,150,5,2,0
7225,2015-06-30 22:45:00,13,0,0,0,0,0,0,0,0,...,0,0,298.06,61,1011,0,150,5,2,0
7392,2015-06-30 23:14:00,11,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0
7552,2015-06-30 23:42:00,10,0,0,0,0,0,0,0,0,...,0,0,297.30,69,1011,0,150,5,2,0

In [ ]:
#plots
m.plot(forecast)
m.plot_components(forecast)

In [ ]:
#correct vs prediction
comp = df.loc[1315040:,['ds','y']]
comp['yhat'] = forecast['yhat']
comp

In [ ]:
#evaluation metric
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import numpy as np

comp_ar = comp.values
y_true = comp_ar[:,1]
y_pred = comp_ar[:,2]
mean_sq_err = mean_squared_error(y_true, y_pred)
mean_abs_err = mean_absolute_error(y_true, y_pred)